name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # or specify any branch you'd like to use for triggering deployments
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v2
        with:
          deliverables: app.yaml
          version: v2
          project_id: "team-gahsp"
      
      - name: Test
        run: 'curl "${{ steps.deploy.outputs.version_url }}"'
