name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # or specify any branch you'd like to use for triggering deployments

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet
